# Generated by Django 5.0.6 on 2024-06-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2A', '2А'), ('2Б', '2Б'), ('3A', '3А'), ('3Б', '3Б')], default='1А', max_length=2, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2A', '2А'), ('2Б', '2Б'), ('3A', '3А'), ('3Б', '3Б')], default='1А', max_length=2, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2A', '2А'), ('2Б', '2Б'), ('3A', '3А'), ('3Б', '3Б')], default='1А', max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2A', '2А'), ('2Б', '2Б'), ('3A', '3А'), ('3Б', '3Б')], default='1А', max_length=2, verbose_name='Осень')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('fam', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otc', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('PN', 'Запрос рассматривается'), ('AC', 'Запрос успешно принят'), ('RJ', 'Запрос не принят')], default='NW', max_length=2)),
                ('beauty_title', models.CharField(max_length=255, verbose_name='перевал')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('other_title', models.CharField(max_length=255, verbose_name='другие названия')),
                ('connect', models.TextField(verbose_name='соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coord', verbose_name='координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='уровень сложности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.user', verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2083)),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.perevaladded')),
            ],
        ),
    ]
